Repository 2024-Winter-BootCamp-TeamF/Frontend, pull requests merged in 2025-01, with the labels that each got.

#3 [feat/#1] 이미지 추가 완료
  src/images/add.png
  src/images/character.png
  src/images/correct.png
  src/images/delete.png
  src/images/footer.png
  src/images/logo.svg
  src/images/main_background.png
  src/images/mypage.png
  src/images/mypage_note.png
  src/images/mypage_praactice.png
  src/images/mypage_summary.png
  src/images/note.png
  src/images/practice.png
  src/images/sub_background.png
  src/images/summary.png
  src/images/wrong.png
Labels: good first issue

#13 [FEAT] button
  src/components/button.jsx
  src/components/ㅁ
Labels: 기능구현

#17 [FIX] SampleButton, SolveButton
  README.old.md
  src/components/ SampleButton.jsx
  src/components/SolveButton.jsx
Labels: 디자인

#18 [FEAT] Download, Ex Button
  src/components/DownloadButton.jsx
  src/components/ExButton.jsx
Labels: 디자인

#21 [DESIGN] 버튼 컴포넌트명 및 export 수정
  src/components/DownloadButton.jsx
  src/components/ExButton.jsx
  src/components/SampleButton.jsx
  src/components/SolveButton.jsx
  src/components/index.js
Labels: 디자인

#24 [DESIGN] MyPage - summary
  package.json
  src/App.js
  src/components/ExButton.jsx
  src/pages/UserPage.jsx
Labels: 디자인

#28 [DESIGN] SamplePage - 요약본 생성 페이지
  package-lock.json
  package.json
  src/App.js
  src/components/ExButton.jsx
  src/pages/SamplePage.jsx
Labels: 디자인

#26 [DESIGN] MyPage - Ex, Note
  package-lock.json
  package.json
  src/App.js
  src/images/mypage_practice.png
  src/pages/UserPageEx.jsx
  src/pages/UserPageNote.jsx
  src/pages/ㅁ
Labels: 디자인

#29 [DESIGN] LoginPage - 로그인/회원가입 페이지
  src/components/LoginBox.jsx
  src/components/LoginInputForm.jsx
  src/components/LoginToggle.jsx
  src/components/SignIn.jsx
  src/components/SignUp.jsx
  src/images/login_user.png
  src/images/user.png
  src/pages/LoginPage.jsx
Labels: 디자인

#33 [DESIGN] 채점/문제생성/추가문제생성 완료 페이지 (CheckCompletePage, PracticeCompletePage, AdditionalCompletePage)
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/SolveButton.jsx
  src/pages/AdditionalCompletePage.jsx
  src/pages/CheckCompletePage copy.jsx
  src/pages/PracticeCompletePage.jsx
  src/styles/theme.js
Labels: 디자인

#35 [Design] 강의자료 업로드 페이지 (UploadPage)
  src/App.js
  src/pages/UploadPage.jsx
  src/pages/UserPageSample.jsx
Labels: 디자인

#36 [DESIGN] 메인 페이지 (MainPage)
  src/components/Banner.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Introduce.jsx
  src/components/SignIn.jsx
  src/components/SignUp.jsx
  src/images/character.png
  src/images/circles.png
  src/images/main_background.png
  src/pages/MainPage.jsx
Labels: 디자인

#39 [DESIGN] 로그인/회원가입 페이지 (LoginPage) 디자인 수정
  package.json
  src/components/LoginBox.jsx
  src/components/LoginInputForm.jsx
  src/components/LoginToggle.jsx
  src/pages/LoginPage.jsx
Labels: 디자인

#45 [FEAT] 마이페이지 - 연습문제, 요약, 오답노트 라우팅 및 일부 수정
  src/App.js
  src/components/ExButton.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/pages/UploadPage.jsx
  src/pages/UserPageEx.jsx
  src/pages/UserPageNote.jsx
  src/pages/UserPageSample.jsx
Labels: 기능구현, 이슈해결

#44 [FEAT] 로그인/회원가입 페이지(LoginPage) 및 헤더(Header) 기능 구현
  src/App.js
  src/components/Header.jsx
  src/components/LoginBox.jsx
  src/components/LoginInputForm.jsx
Labels: 기능구현

#50 Feat/#41 연습문제 디자인 기능
  src/App.js
  src/App.jsx
  src/components/SolveButton.jsx
  src/pages/GradingResults.jsx
  src/pages/NotePage/ConceptExplanation.jsx
  src/pages/NotePage/WrongAnswer.jsx
  src/pages/NotePage/WrongProblemList.jsx
  src/pages/PracticePage/MultipleChoice.jsx
  src/pages/PracticePage/ProblemContent.jsx
  src/pages/PracticePage/ProblemList.jsx
  src/pages/PracticePage/Subjective.jsx
  src/pages/PracticePage/data.jsx
Labels: 오류수정

#55 [Feat] 요약본 생성 페이지 기능 구현
  public/compressed.tracemonkey-pldi-09.pdf
  src/images/Extension.png
  src/images/reduction.png
  src/pages/SamplePage.jsx
Labels: 기능구현

#57 [FEAT] UploadPage - 버튼 수정 및 로딩 모달 창 추가
  package.json
  src/App.js
  src/pages/UploadPage.jsx
Labels: 기능구현

#59 [DESIGN] 메인페이지, 요약본 미리보기 페이지 디자인 수정
  src/components/ExButton.jsx
  src/components/Header.jsx
  src/images/Extension (2).png
  src/images/mypage_note.png
  src/images/reduction (2).png
  src/pages/AdditionalCompletePage.jsx
  src/pages/CheckCompletePage.jsx
  src/pages/MainPage.jsx
  src/pages/PracticeCompletePage.jsx
  src/pages/SamplePage.jsx
  src/pages/UserPageEx.jsx
  src/pages/UserPageNote.jsx
  src/pages/UserPageSample.jsx
Labels: 디자인

#60 [FEAT] pdf 업로드 후 pdf 뷰어 기능 구현
  public/compressed.tracemonkey-pldi-09.pdf
  src/pages/SamplePage.jsx
  src/pages/UploadPage.jsx
Labels: 기능구현

#65 [DESIGN] 업로드 페이지 디자인 수정
  src/components/SampleButton.jsx
  src/pages/UploadPage.jsx
Labels: 디자인

#66 [FEAT] 채점/문제생성/추가문제생성 완료 페이지 (CheckCompletePage, PracticeCompletePage, AdditionalCompletePage) 기능구현
  src/pages/AdditionalCompletePage.jsx
  src/pages/CheckCompletePage.jsx
  src/pages/PracticeCompletePage.jsx
Labels: 기능구현

#71 [Feat] 학습자료 업로드/요약본 api 연동
  package-lock.json
  src/axiosInstance.js
  src/components/LoginInputForm.jsx
  src/pages/SamplePage.jsx
  src/pages/UploadPage.jsx
Labels: 기능구현

#73 feat) 강의자료 업로드 페이지 디자인 수정
  src/pages/UploadPage.jsx
Labels: 디자인

#68 [DESIGN] 연습 문제 풀이, 오답노트 페이지 디자인 수정
  src/images/confused.png
  src/images/correct.png
  src/pages/NotePage/ConceptExplanation.jsx
  src/pages/NotePage/WrongAnswer.jsx
  src/pages/NotePage/WrongProblemList.jsx
  src/pages/PracticePage/MultipleChoice.jsx
  src/pages/PracticePage/ProblemContent.jsx
  src/pages/PracticePage/ProblemList.jsx
  src/pages/PracticePage/Subjective.jsx
  src/pages/PracticePage/data.jsx
Labels: 디자인

#75 [FEAT] SamplePage 수정
  src/components/SampleButton2.jsx
  src/pages/SamplePage.jsx
Labels: 기능구현

#84 [feat] 요약본 마이페이지에 연결하기
  src/pages/SamplePage.jsx
  src/pages/UploadPage.jsx
  src/pages/UserPageSample.jsx
Labels: 기능구현

#85 [FEAT] 연습문제 생성 API 연동 / 연습 문제 풀이 페이지 기능 구현
  src/pages/CreatePracPage.jsx
  src/pages/PracticeCompletePage.jsx
  src/pages/PracticePage/MultipleChoice.jsx
  src/pages/PracticePage/ProblemContent.jsx
  src/pages/PracticePage/ProblemList.jsx
  src/pages/PracticePage/Subjective.jsx
  src/pages/SamplePage.jsx
  src/pages/UploadPage.jsx
Labels: 기능구현

#87 [FEAT] 샘플 페이지 디자인 오류 수정
  src/pages/SamplePage.jsx
Labels: 디자인

#91 [FEAT] 연습 문제 생성본 - 마이페이지 연결
  src/pages/CreatePracPage.jsx
  src/pages/PracticeCompletePage.jsx
  src/pages/PracticePage/MultipleChoice.jsx
  src/pages/PracticePage/ProblemContent.jsx
  src/pages/PracticePage/ProblemList.jsx
  src/pages/PracticePage/Subjective.jsx
  src/pages/UserPageEx.jsx
Labels: 기능구현

#93 [FEAT] 채점 API 연동
  src/pages/GradingResults.jsx
  src/pages/PracticePage/MultipleChoice.jsx
  src/pages/PracticePage/ProblemContent.jsx
  src/pages/PracticePage/ProblemList.jsx
  src/pages/PracticePage/Subjective.jsx
Labels: 기능구현

#99 [Feat] 오답 조회 api 연동
  src/pages/GradingResults.jsx
  src/pages/NotePage/WrongAnswer.jsx
  src/pages/PracticePage/MultipleChoice.jsx
  src/pages/PracticePage/ProblemContent.jsx
Labels: 기능구현

#100 [DESIGN] 채점 기능 수행 후 문제에 적용되는 스타일 수정
  src/pages/GradingResults.jsx
  src/pages/PracticePage/MultipleChoice.jsx
  src/pages/PracticePage/Subjective.jsx
Labels: 디자인

#105 [FEAT] 오답노트 생성본 마이페이지에 연결
  src/pages/CreatePracPage.jsx
  src/pages/GradingResults.jsx
  src/pages/NotePage/WrongAnswer.jsx
  src/pages/PracticePage/ProblemContent.jsx
  src/pages/SamplePage.jsx
  src/pages/UploadPage.jsx
  src/pages/UserPageNote.jsx
Labels: 기능구현

#107 [FEAT] 문제 생성 페이지 파인콘 업로드 API 연동 및 모달창 구현
  src/pages/CreatePracPage.jsx
  src/pages/UploadPage.jsx
Labels: 기능구현

#110 [FEAT] 요약본 저장 시 이름, 날짜 형태 자동 지정 기능 구현
  src/pages/SamplePage.jsx
  src/pages/UserPageSample.jsx
Labels: 기능구현

#115 [FEAT] 채점 페이지 답안 출력 기능 구현
  src/pages/MorePracticePage/MoreMultipleChoice.jsx
  src/pages/MorePracticePage/MoreSubjective.jsx
  src/pages/PracticePage/MultipleChoice.jsx
  src/pages/PracticePage/Subjective.jsx
Labels: 기능구현

#119 [DESIGN] 연습 문제, 추가 연습 문제 생성 / 채점 / 요약본 불러오기 로딩 모달 구현
  src/pages/CreatePracPage.jsx
  src/pages/MorePracticePage/MoreProblemContent.jsx
  src/pages/NotePage/WrongAnswer.jsx
  src/pages/PracticeCompletePage.jsx
  src/pages/PracticePage/ProblemContent.jsx
  src/pages/SamplePage.jsx
Labels: 디자인

#123 [FIX] 전체 API 엔드포인트 수정 및 파인콘 업로드 API 엔드포인트 경로 수정
  src/components/LoginInputForm.jsx
  src/pages/AdditionalCompletePage.jsx
  src/pages/CreatePracPage.jsx
  src/pages/MorePracticePage/MoreProblemContent.jsx
  src/pages/MorePracticePage/MoreWrongAnswer.jsx
  src/pages/NotePage/WrongAnswer.jsx
  src/pages/PracticeCompletePage.jsx
  src/pages/PracticePage/ProblemContent.jsx
  src/pages/SamplePage.jsx
  src/pages/UploadPage.jsx
  src/pages/UserPageEx.jsx
Labels: 이슈해결

#125 [Feat] 헷갈리는 문제 마이페이지에 보이도록
  src/pages/GradingResults.jsx
  src/pages/NotePage/WrongAnswer.jsx
  src/pages/PracticePage/ProblemContent.jsx
Labels: 기능구현, 디자인

#129 [DESIGN] 디자인 디테일 수정 (CreatePracPage, GradingResults) 및 파인콘 데이터 삭제 API 연동
  src/pages/AdditionalCompletePage.jsx
  src/pages/CreatePracPage.jsx
  src/pages/MorePracticePage/MoreWrongAnswer.jsx
  src/pages/NotePage/WrongAnswer.jsx
  src/pages/PracticeCompletePage.jsx
  src/pages/PracticePage/Subjective.jsx
  src/pages/SamplePage.jsx
Labels: 기능구현, 디자인

#130 [FEAT] 헷갈리는 문제 너 아웃!
  src/pages/MorePracticePage/MoreMultipleChoice.jsx
Labels: 디자인

#135 [FEAT] 디자인 수정사항 등등
  src/pages/MorePracticePage/MoreWrongAnswer.jsx
  src/pages/SamplePage.jsx
  src/pages/UploadPage.jsx
Labels: 디자인

#134 [FIX] 문제 유형 업로드 API 교체
  src/pages/CreatePracPage.jsx
Labels: 이슈해결

#136 [DESIGN] 메인 페이지 디테일 수정
  src/App.js
  src/components/Banner.jsx
  src/components/Introduce.jsx
  src/components/ScrolToTop.jsx
  src/images/Extension (2).png
  src/images/Extension.png
  src/images/SampleEx.png
  src/images/docs.png
  src/images/pen.png
  src/images/reduction (2).png
  src/images/reduction.png
  src/images/마이페이지.png
  src/images/문제 생성 과정.png
  src/images/문제 예시.png
  src/images/오답노트.png
  src/pages/GradingResults.jsx
  src/pages/NotePage/WrongAnswer.jsx
  src/pages/PracticePage/ProblemContent.jsx
  src/pages/SamplePage.jsx
  src/pages/UploadPage.jsx
Labels: 디자인

#138 [DESIGN] 추가 오답노트 페이지 디자인 수정
  src/pages/MorePracticePage/MoreWrongAnswer.jsx
Labels: 디자인

#140 [DESIGN] 회원가입 시 모달창 출력
  src/components/LoginInputForm.jsx
Labels: 디자인
